project:
  type: website
  output-dir: _site

website:
  title: "Sofia Fabian"
  description: "Postdoctoral researcher in hydrology and climate science"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: article
