---
title: "About"
---

I'm Sofia Fabian, a postdoctoral researcher in hydrology and climate science.

I'm a chemical engineer by training, with three and a half years of R&D experience at a semiconductor company before moving into research. A diverse background that taught me to value an independent strong work ethic, and leaning into own curiosity and serendipity. I've always believed that to research, is to know, to understand, and to solve. I'm now orienting toward the space where climate and environmental modeling meets policy decision. 

I love tennis, but can't guarantee I'm good at it.I love camping and I bet it loves me back :)


## Background

Postdoctoral Researcher, Sejong University — 03.2025 – *Present*\
PhD, Civil and Environmental Engineering, Sejong University — 03.2023 – 02.2025\
MS, Civil and Environmental Engineering, Dongguk University — 03.2020 – 02.2022\
BS, Chemical Engineering, Mapua University — 08.2011 – 02.2016\
R&D Engineer & Product Technical Team Leader, Samsung Electro-Mechanics — 09.2016 – 02.2020


## Contact
- **Email** — psdfabian@gmail.com
- **LinkedIn** — [in/pamelasofiafabian](https://www.linkedin.com/in/pamelasofiafabian/)
- **Research Gate** — [Profile](https://www.researchgate.net/profile/Pamela-Sofia-Fabian)
- **ORCID** — [0000-0002-9196-212X](https://orcid.org/0000-0002-9196-212X)

---


